# Generated by Django 3.2.6 on 2021-08-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fake',
            field=models.CharField(default='Yes', max_length=12),
        ),
    ]
